### ISSUE TITLE
Migrate to the new dart-sass API

### ISSUE THREAD

**Issue by binyamin** [AramZS/eleventy-plugin-dart-sass#1] opened 2021-12-30 23:29 UTC
[In v1.45.0](https://github.com/sass/dart-sass/releases/tag/1.45.0), dart-sass introduced a new JavaScript API. The old API will be removed in v2.0.0. https://sass-lang.com/documentation/js-api

**Comment by AramZS** [comment] 2021-12-30 23:45
Yup, I'm aware of the upcoming depreciation. I locked the minor version in `package.json`, [informed users](https://github.com/AramZS/eleventy-plugin-dart-sass#current-dart-sass-version-note), and intend to get to the upgrade once the need becomes more urgent. I will also be glad to take PRs to make the change (I would welcome them in fact!) but the new interface looks like a fairly large change from the old one and alters some of the logic around source maps, so I'll need to take some time in the future to wrap my head around it before I make the change. 

I'm going to close this for now because I'm aware of the issue and the change is incoming in the future and the issue is also documented clearly to users and does not impact current (or even future) functionality beyond potentially forcing the user to have two versions of Sass in their project. 

Thanks for the heads up!

**Closed as completed by AramZS** 2021-12-30 23:46 UTC

**Comment by binyamin** [comment] 2021-12-31 00:04
@AramZS Thanks for your response. And, for taking the time to do something beyond slapping an "invalid" label on it :smile:. Happy New Years!

**Comment by AramZS** [comment] 2021-12-31 01:19
You too @binyamin !

**Comment by binyamin** [comment] 2022-01-02 19:08
@AramZS I wrote an implementation. https://github.com/binyamin/eleventy-plugin-sass

**Comment by AramZS** [comment] 2022-03-01 20:55
@binyamin I'll check it out as a guide for maybe running an upgrade here!
